# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CMPConsentToolDemoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CMPConsentToolDemoApp

  pod 'PrebidMobile'
  pod 'AppNexusSDK'
  pod 'mopub-ios-sdk'
  pod 'Google-Mobile-Ads-SDK'

end
